set -g mouse on
setw -g mode-keys vi
set -g status-bg cyan
set -g @plugin 'christoomey/vim-tmux-navigator'

# change prefix key 
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g default-terminal "xterm-256color"

# run plugin manager
run '$HOME/.config/tmux/plugins/tpm/tpm'
